name: prestoncarter
favicon: null
layout_spectrum: 0.2535089747980237
typography_spectrum: 0.2770808613859117
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9542069812305272
  lightness: 0.04804955911822617
  saturation: 0.003552173962816596
  rhythmicContrast: 0.7005461372900754
purpose: []
